## Difference between Numpy and list
 list are not very compact. list can have element of different type. list are generally slow.

 Numpy arrays are fast. they have elements of same type

In [3]:
import math as m
m.sqrt(5)

2.23606797749979

In [16]:
import numpy as np
l=["23","ds","sdf"]
l=np.array(l)
print(l.dtype)

print(np.zeros(10))
a=np.ones(10)
print(type(a))
print(a.dtype)

b=np.zeros(5,int) 
print(type(b))
print(b.dtype)

print(np.zeros((2,3,3))) # to create 3d array pass tuple as input

<U3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
float64
<class 'numpy.ndarray'>
int32
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [24]:
b=np.array([1,2,3,4])
print(b)

b[0]='8' # automatically convert to int
print(b)

# b[0]='a' error

#slicing
print(b[2:4])

print(b.shape)

[1 2 3 4]
[8 2 3 4]
[3 4]
(4,)


In [36]:
a=[[1,2,3],[4,5,6],[4,9,8],[7,5,9]]  # 2d list
a=np.array(a)
print(a[0][0:2])
print(a[0])  # eccess row
print(a[:,0]) # eccess 0th column (valid only for numpy arrays) 
print(a[0:2,0]) # slicing in 0th column
print(a[2:,:])  #printing two lower rows
print(a[1:3,1:])

# thus we can get any subarray

[1 2]
[1 2 3]
[1 4 4 7]
[1 4]
[[4 9 8]
 [7 5 9]]
[[5 6]
 [9 8]]


In [41]:
print(np.arange(10))
print(np.arange(4,9))
print(np.arange(1,10,3))

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8]
[1 4 7]


In [49]:
# operation on numpy array and how they are different from list

l=[1,2,3,4]
a=np.array([1,2,3,4])

print(l+l) # append list by itself
print(a+a) # each element of a is added to each element of a

b=np.array([1,2,3])
 # print(a+b) => error

#print(l+2) => error
print(a+2) # add 2 to each element to a

print(l*3) # append itself two times
print(a*3) # multiply each element by 3

# print(l-l)  error
print(a-a)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
[3 4 5 6]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[ 3  6  9 12]
[0 0 0 0]


In [56]:
a=np.array([1,2,3,4,5])
print(a.mean())
print(a.sum())
print(a.max())
print(a.min())

3.0
15
5
1


In [61]:
# numpy arrays are easy for some calculations
# let N dimensional space, p1(point 1)=[1,2,3...n] and p2(point 2)=[1,2,3.....n]
# we want to calculate squared distance between two points  ((x1-y1)^2+(x2-y2)^2+......)^0.5

# 3D space
a=np.array([1,2,3])
b=np.array([3,4,5])

c=(a-b)**2
d=c.sum()
distance = d**0.5
print(distance)

3.4641016151377544


In [69]:
# variance calculate
a=np.array([1,2,3,4,5,6,7,-1,-5,0,5])
mean=a.mean()
print(mean)
b=a-mean
#print(b)
c=b**2
#print(c)
variance=c.sum()
print(variance)
sd=m.sqrt(variance)
print(sd)

2.4545454545454546
124.72727272727273
11.16813649304452


In [70]:
# Dot product
a=np.array([1,2,3,4])
b=np.array([4,5,6,0])
a.dot(b)


32

In [79]:
a=np.array([[1,2,3],[1,2,3]])
print(a.sum())
np.sum(a,axis=1)

12


array([6, 6])

In [75]:
# Numpy Matrices
a=np.mat('2,3,4;2,3,4;1,1,1')
a*a # matrix product



matrix([[14, 19, 24],
        [14, 19, 24],
        [ 5,  7,  9]])